### ISSUE TITLE
2560x1440 resolution does not fit the screen with the native resolution of 2560x1440

### ISSUE THREAD

**Issue by Alexander-Serov** [Return-To-The-Roots/s25client#1066]
See attached fullscreen-mode screenshots. All other apps work fine.

Additional info: I'm using standard Windows 125% scaling, but it never affects full-screen apps. Worth checking?

Thanks for your efforts!

![bug_view](https://user-images.githubusercontent.com/22743277/59159584-452c3f80-8acc-11e9-8640-d569dc36c689.jpg)
![screen resolution](https://user-images.githubusercontent.com/22743277/59159587-4c534d80-8acc-11e9-901f-b54102c33d7e.png)
![bug_view2](https://user-images.githubusercontent.com/22743277/59159611-a9e79a00-8acc-11e9-9a5d-a5ef325925ff.jpg)

**Comment by Flow86** [comment]
Its not a fullscreen app, its only borderless window. We have to check. There should be some kind of flag to automatically disable screen scaling for this app

**Comment by Flamefire** [comment]
Can you try SDL2 as the graphics driver?

@Flow86 I think it is now really fullscreen after some fixes a while ago. At least what SDL considers fullscreen

**Comment by Alexander-Serov** [comment]
I have checked with SDL2. The window then fits the screen, however the resolution is wrong. The options say it's still 2560x1440, but the text looks grained and when I take screenshots, they are 1920x1440. Also, other screen formatting bugs appear like this one (shifted text):
![image](https://user-images.githubusercontent.com/22743277/60394019-eaf82a80-9b1d-11e9-87cc-75babc0b238c.png)
or with black sides of the screen.

**Comment by Spikeone** [comment]
I also use WQHD and I tried out the latest nightly build and can't reproduce that fault. I tried it with SDL and SDL2, no error there.

But I got another problem, when running the game with WINAPI the game doesn't even start anymore.

Starting in F:\s25rttr_20190627 
Searching for drivers in F:\s25rttr_20190627\driver/video
3 video drivers found!
Loaded video driver "(WinAPI) OpenGL via the glorious WinAPI"


FATAL ERROR: Failed to initialize the OpenGL context!



ERROR: Failed to start the game


Press ENTER to close this window . . . `

**Comment by Alexander-Serov** [comment]
I confirm: 

- openGL didn't work at all,

- SDL does not fit the screen when Windows zoom is on,

- SDL2 fits the window, but the resolution is incorrect.

**Comment by Flow86** [comment]
@Flamefire 
I think I finally found the topic about dpi awareness I searched for the last weeks: https://discourse.libsdl.org/t/sdl-getdesktopdisplaymode-resolution-reported-in-windows-10-when-using-app-scaling/22389

**Comment by Flamefire** [comment]
Working on it. Your thread confirms what I found too. There are other, related bugs I fixed already locally. I'll test things later this week

**Comment by Flow86** [comment]
fixed by e20237569f78732012b608420bfbcba5af121541

Tested it with windows 10 and 125% scaling.

**Comment by Alexander-Serov** [comment]
Thank you. I will be glad to test it when the new build becomes available!

**Comment by Alexander-Serov** [comment]
v20190706-90d4fe80cff72e57b7e604ba6eefb85a7985f97c does not solve the original issue yet. However, the graphics got more pixelized and less smooth.

**Comment by Flamefire** [comment]
This is strange. Go to settings, check whether you are using sdl2 and full screen with full resolution.

The original issue (cropped content) should be solved. Less smooth is possible as in "more sharp" as no smoothing rescaling is done

**Comment by Alexander-Serov** [comment]
Yes, sorry, you are right. SDL2 solves the original issue. However, less smooth is not as in "more sharp", but as in "hard to read". :) Compare the 2 images below.

SDL2 - Windows 125% scaling
![SDL2-125](https://user-images.githubusercontent.com/22743277/61153422-7f359a80-a4eb-11e9-980a-a571c99b3083.png)

SDL2 - Windows 100% scaling
![SDL2-100](https://user-images.githubusercontent.com/22743277/61153436-8d83b680-a4eb-11e9-89df-f2ccc23c9c57.png)

I don't know if you can see the difference on your screen, but the 2nd one is much easier to read.

**Comment by Alexander-Serov** [comment]
Don't take the white bars into account. The screen fits correctly. It just the screenshots are weird at 125%.

**Comment by Alexander-Serov** [comment]
Which probably supports the point that there is still something weird about SDL2 and 125%...

**Comment by Alexander-Serov** [comment]
What is still surprising for me is that I have never experienced something similar in any game. I never had to reset the Windows app scaling for any other.
