### ISSUE TITLE
some localization is missing

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1568]
hey, I just noticed a few missing localizations in current git master. 

the screen of `Receiving mapdata` is in english

the options for `Military aid` are in english only 

Economy mode is in english only

**Comment by Spikeone** [comment]
Wrong project, please report language issues here: https://github.com/Return-To-The-Roots/languages

everybody is welcome to contribute to them :)

**Comment by stefson** [comment]
well, for the non existing german localization of `Receiving map` there is an entry in the rttr-de.po, it should state `Prüfe Karte` instead of displaying the english.

**Comment by Spikeone** [comment]
@Flamefire well he is right, the text is not translated in german although there is a german text, thats why I didn't close this issue but guessed that this is either a missing import or a bug of some sort

**Comment by Flamefire** [comment]
It seems this is fixed now. Tested with a fresh compile and current nightly.
@Spikeone can you confirm?

**Comment by Spikeone** [comment]
@Flamefire can confirm that "Prüfe Karte..." is shown correctly - those missing entries, well are still missing
