### ISSUE TITLE
s25update fails on Ubuntu

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#2]
When trying to start s25rttr through rttr.sh, there is no progress after the following message appears:

```
checking for an update ...
```

When executing /share/s25rttr/RTTR/s25update directly the following message appears reproducibly:

```
Updating "s25client":                                            100.00% - ok
Updating "libaudioSDL.so":                                       100.00% - ok
Updating "put your S2-Installation in here":                      -nan% - decompression failed: download failure?
```

No progress after that.

**Comment by Flow86** [comment]
fixed by 7752f3d6e1fa11342f49d02427c6306583b54f2b

**Comment by mplatt** [comment]
This still happens also with the newest nightly build available for download (s25rttr_20150601):

```
...
Updating "Eigen.swd":                                            100.00% - ok
Updating "DINOLAND.SWD":                                         100.00% - ok
Updating "BUCC.SWD":                                             100.00% - ok
Updating "wbab_z.lst":                                           100.00% - ok
Updating "AUSTRIA.SWD":                                          100.00% - ok
Updating "Gltschrg.swd":                                         100.00% - ok
Updating "put your S2-Installation in here":                      -nan% - decompression failed: download failure?
```
