### ISSUE TITLE
[LUA] one Sided alliances

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#743]
The original game allowed one sided alliances. 

What does it mean? Well, it disallows one player to attack an other player as they are allied. While player A can't attack player B, player B can attack player A. Also catapults do not break this but I think that was a bug in the original.

![image](https://user-images.githubusercontent.com/1276342/32668920-2c1fc8c0-c63f-11e7-8f5e-ac977b1d16d4.png)

So in this example:
player A = Player, can attack player B and C
player B = Computer, can attack player C
player C = Computer, can't attack anyone.

What is this needed for? Well for the original missions. The AI could expand as far as the AI liked to but could not attack the player unless the player attacked the AI first. That way an AI was just blocking but not agressive. 

I do not think we should implement the original bug, that you could use catapults without breaking the one sided pact as attacking results in a broken alliance, catapults did not.

**Comment by Spikeone** [comment]
Well, it's not that important how it works internally, but the player should be able to attack to cancel the pact for the AI, maybe an other version as the non agressive pact which allows attacking to cancel?

**Comment by Flamefire** [comment]
Wait. A pact that disallows attacking unless someone is attacking?
Nope...

**Comment by Spikeone** [comment]
Well, for one player - but if the AI coulld be non agressive towards the player until the AI is atfacked, that would solve the problem as well

**Comment by Flamefire** [comment]
Fixed in #773

**Comment by Spikeone** [comment]
@Flamefire this still does not allow the following:
In the 2nd Mission, the AI player is friendly towards the player unless he attacks. This gives the player time to do whatever he wants and attack whenever he wants to.
Regarding the pact logic we currently have, it is not possible to do so as well, is it?

I think the main idea behind those pacts aren't infact pacts, but merely a "do not attack until attacked". Can we implement such option for the AI? So we may set right at the start rttr:GetPlayer(1):SetDefensiveLevel(1)
Where 0 = normal (as is), 1 = don't attack until attack (1 sided pacts) and 2 = do not attack?

That way we can leave pacts as they are but have the same outcome.

**Comment by Flamefire** [comment]
Well the sequence would be: Player and AI have pact so none can attack. Player sends cancel pact to AI, AI is set to accept, player attacks AI. This is mostly the same, isn't it? Only difference is that the trigger is a cancel pact request instead of an attack.

If you'd really want that nicer behavior we'd need better names. And I'd suggest a target player to:

`GetPlayer(1).SetAggression(0, [Aggressive, Peaceful, Pacifistic])` or so which avoids the magic numbers

**Comment by Spikeone** [comment]
Well, I simply don't think it's convenient to expect the player to actively cancel a pact.

And yes sure, the naming was just for showing what I thought about. Also like your idea of setting the target player, I simply thought it'd be harder to implement. Maybe we also need a onAttack event, if for example 2 AIs are peaceful, but only one is attacked but both should switch to agressive then.

**Comment by Flow86** [comment]
what about giving the player the option to attack, but always ask the user first: "you have a peace treaty with this player. Do you really want to attack?"

**Comment by Flamefire** [comment]
Wouldn't do that: A peace treaty should not be broken before it expires or it would be pointless. This is not Game Of Thrones ;)

**Comment by Flow86** [comment]
yes i meant that you could allow that behaviour via LUA

**Comment by Spikeone** [comment]
@Flamefire @Flow86 Also this one feels important, as users report impossible to beat maps (which wasn't the case in the original since players could decide on when to fight)

**Comment by kejoat** [comment]
Second this, S2 campaign feels quite different (and much harder) than original because of this.
